using System.Text;
using System.Text.Json;
using Microsoft.Data.Sqlite;

namespace McpSqlServer;

public record ServerRegistryItem(
    string ServerAlias,
    string ServerHost,
    string ServerVersion,
    int DatabaseCount,
    int TotalTableCount,
    int TotalViewCount,
    int TotalProcedureCount,
    DateTime LastScannedAt,
    int TotalFunctionCount = 0,
    int TotalTriggerCount = 0,
    IReadOnlyDictionary<string, DatabaseMigrationStatus>? Migrations = null
);

public record SearchContextMatch(
    string ServerAlias,
    string Database,
    string Type,
    string Name,
    string Details,
    string RelativePath
);

public record SearchContextResult(
    string Query,
    int TotalMatches,
    IReadOnlyList<SearchContextMatch> Matches,
    string Message
);

public class AiContextRenderer
{
    public static async Task<IReadOnlyList<string>> RenderAndExportAsync(
        ServerScanResult scanResult,
        string outputDirectory = "./ai-context",
        CancellationToken cancellationToken = default)
    {
        var createdFiles = new List<string>();
        var baseDir = Path.GetFullPath(outputDirectory);
        var serversDir = Path.Combine(baseDir, "servers");
        var serverDir = Path.Combine(serversDir, scanResult.ServerAlias);

        Directory.CreateDirectory(serverDir);

        // Delete legacy monolithic GLOBAL_TABLES_MAP.compact.md to eliminate token trap
        var legacyGlobalMap = Path.Combine(serverDir, "GLOBAL_TABLES_MAP.compact.md");
        if (File.Exists(legacyGlobalMap))
        {
            try { File.Delete(legacyGlobalMap); } catch { }
        }

        // 1. Export schema files, views, procedures, functions, triggers
        int scanTotalTables = 0;
        int scanTotalViews = 0;
        int scanTotalProcedures = 0;
        int scanTotalFunctions = 0;
        int scanTotalTriggers = 0;

        var scannedDbNames = new HashSet<string>(scanResult.Databases.Select(d => d.DatabaseName), StringComparer.OrdinalIgnoreCase);

        foreach (var db in scanResult.Databases)
        {
            cancellationToken.ThrowIfCancellationRequested();

            scanTotalTables += db.TableCount;
            scanTotalViews += db.ViewCount;
            scanTotalProcedures += db.ProcedureCount;
            scanTotalFunctions += db.FunctionCount;
            scanTotalTriggers += db.TriggerCount;

            if (!db.Success) continue;

            var dbDir = Path.Combine(serverDir, "databases", db.DatabaseName);
            var viewsDir = Path.Combine(dbDir, "views");
            var procsDir = Path.Combine(dbDir, "procedures");
            var funcsDir = Path.Combine(dbDir, "functions");
            var trgsDir = Path.Combine(dbDir, "triggers");

            Directory.CreateDirectory(dbDir);
            if (db.Views.Count > 0) Directory.CreateDirectory(viewsDir);
            if (db.Procedures.Count > 0) Directory.CreateDirectory(procsDir);
            if (db.Functions.Count > 0) Directory.CreateDirectory(funcsDir);
            if (db.Triggers.Count > 0) Directory.CreateDirectory(trgsDir);

            // Write schema.compact.md
            var compactSchemaPath = Path.Combine(dbDir, "schema.compact.md");
            var compactContent = RenderCompactSchema(scanResult.ServerAlias, db);
            await File.WriteAllTextAsync(compactSchemaPath, compactContent, Encoding.UTF8, cancellationToken);
            createdFiles.Add(compactSchemaPath);

            // Cleanup orphan routine files that no longer exist on database
            CleanupOrphanSqlFiles(viewsDir, db.Views.Select(v => SanitizeFileName($"{v.Schema}.{v.Name}.sql")));
            CleanupOrphanSqlFiles(procsDir, db.Procedures.Select(p => SanitizeFileName($"{p.Schema}.{p.Name}.sql")));
            CleanupOrphanSqlFiles(funcsDir, db.Functions.Select(f => SanitizeFileName($"{f.Schema}.{f.Name}.sql")));
            CleanupOrphanSqlFiles(trgsDir, db.Triggers.Select(t => SanitizeFileName($"{t.Schema}.{t.Name}.sql")));

            // Write individual View SQL files
            foreach (var view in db.Views)
            {
                var safeViewName = SanitizeFileName($"{view.Schema}.{view.Name}.sql");
                var viewPath = Path.Combine(viewsDir, safeViewName);
                var viewSql = $"-- Server: {scanResult.ServerAlias} | DB: {db.DatabaseName} | View: {view.FullName}\n" +
                              $"-- Auto-generated by MCP SQL Server\n\n" +
                              (view.Definition ?? "-- [Definition unavailable: object may be encrypted or login lacks VIEW DEFINITION permission]");
                await File.WriteAllTextAsync(viewPath, viewSql, Encoding.UTF8, cancellationToken);
                createdFiles.Add(viewPath);
            }

            // Write individual Procedure SQL files
            foreach (var proc in db.Procedures)
            {
                var safeProcName = SanitizeFileName($"{proc.Schema}.{proc.Name}.sql");
                var procPath = Path.Combine(procsDir, safeProcName);
                var paramsHeader = proc.Parameters.Count > 0
                    ? $"-- Parameters:\n" + string.Join("\n", proc.Parameters.Select(p => $"--   {p}")) + "\n"
                    : "-- Parameters: (None)\n";

                var procSql = $"-- Server: {scanResult.ServerAlias} | DB: {db.DatabaseName} | Procedure: {proc.FullName}\n" +
                              paramsHeader +
                              $"-- Auto-generated by MCP SQL Server\n\n" +
                              (proc.Definition ?? "-- [Definition unavailable: object may be encrypted or login lacks VIEW DEFINITION permission]");
                await File.WriteAllTextAsync(procPath, procSql, Encoding.UTF8, cancellationToken);
                createdFiles.Add(procPath);
            }

            // Write individual Function SQL files
            foreach (var func in db.Functions)
            {
                var safeFuncName = SanitizeFileName($"{func.Schema}.{func.Name}.sql");
                var funcPath = Path.Combine(funcsDir, safeFuncName);
                var paramsHeader = func.Parameters.Count > 0
                    ? $"-- Parameters:\n" + string.Join("\n", func.Parameters.Select(p => $"--   {p}")) + "\n"
                    : "-- Parameters: (None)\n";

                var funcSql = $"-- Server: {scanResult.ServerAlias} | DB: {db.DatabaseName} | Function: {func.FullName} ({func.TypeDesc})\n" +
                              paramsHeader +
                              $"-- Auto-generated by MCP SQL Server\n\n" +
                              (func.Definition ?? "-- [Definition unavailable: object may be encrypted or login lacks VIEW DEFINITION permission]");
                await File.WriteAllTextAsync(funcPath, funcSql, Encoding.UTF8, cancellationToken);
                createdFiles.Add(funcPath);
            }

            // Write individual Trigger SQL files
            foreach (var trg in db.Triggers)
            {
                var safeTrgName = SanitizeFileName($"{trg.Schema}.{trg.Name}.sql");
                var trgPath = Path.Combine(trgsDir, safeTrgName);
                var trgSql = $"-- Server: {scanResult.ServerAlias} | DB: {db.DatabaseName} | Trigger: {trg.FullName} on [{trg.TargetTable}] ({trg.Events})\n" +
                             $"-- Auto-generated by MCP SQL Server\n\n" +
                             (trg.Definition ?? "-- [Definition unavailable: object may be encrypted or login lacks VIEW DEFINITION permission]");
                await File.WriteAllTextAsync(trgPath, trgSql, Encoding.UTF8, cancellationToken);
                createdFiles.Add(trgPath);
            }
        }

        // 2. Update SQLite Catalog (catalog.db with FTS5)
        var catalogDbPath = await UpdateCatalogDbAsync(baseDir, scanResult.ServerAlias, scanResult.Databases, cancellationToken);
        createdFiles.Add(catalogDbPath);

        // Clean up legacy GLOBAL_TABLES_MAP.compact.md if present
        var legacyMapPath = Path.Combine(serverDir, "GLOBAL_TABLES_MAP.compact.md");
        if (File.Exists(legacyMapPath))
        {
            try { File.Delete(legacyMapPath); } catch { }
        }

        // 3. Write / Merge TABLES_ROUTER.compact.md
        var routerPath = Path.Combine(serverDir, "TABLES_ROUTER.compact.md");
        var existingRouterLines = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (File.Exists(routerPath))
        {
            var lines = await File.ReadAllLinesAsync(routerPath, cancellationToken);
            foreach (var l in lines)
            {
                if (l.StartsWith("- **`") && l.Contains("`**:"))
                {
                    var closeIdx = l.IndexOf("`**:");
                    var db = l.Substring(5, closeIdx - 5);
                    existingRouterLines[db] = l;
                }
            }
        }

        foreach (var db in scanResult.Databases.Where(d => d.Success && d.Tables.Count > 0))
        {
            var tableNames = string.Join(", ", db.Tables.Select(t => t.Name));
            existingRouterLines[db.DatabaseName] = $"- **`{db.DatabaseName}`**: {tableNames}";
        }

        var routerSb = new StringBuilder();
        routerSb.AppendLine($"# Database Tables Router: {scanResult.ServerAlias}");
        routerSb.AppendLine();
        routerSb.AppendLine($"> Ultra-compact skeleton index (~20KB) for low-token database routing.");
        routerSb.AppendLine($"> Flow: Locate database for table -> Open './databases/{{DB}}/schema.compact.md'.");
        routerSb.AppendLine($"> Fast Search: Call MCP tool `search_context(query: \"...\")` (<1ms via SQLite).");
        routerSb.AppendLine($"> Last updated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        routerSb.AppendLine();
        foreach (var kv in existingRouterLines.OrderBy(k => k.Key))
        {
            routerSb.AppendLine(kv.Value);
        }
        await File.WriteAllTextAsync(routerPath, routerSb.ToString(), Encoding.UTF8, cancellationToken);
        createdFiles.Add(routerPath);

        // 4. Write / Merge Cross-Database Dependencies Map
        var crossDbPath = Path.Combine(serverDir, "CROSS_DB_DEPENDENCIES.compact.md");
        var existingDbSections = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        if (File.Exists(crossDbPath))
        {
            var existingLines = await File.ReadAllLinesAsync(crossDbPath, cancellationToken);
            string? currentDb = null;
            var currentSection = new StringBuilder();

            foreach (var line in existingLines)
            {
                if (line.StartsWith("## Database `") && line.EndsWith("`"))
                {
                    if (currentDb != null && currentSection.Length > 0)
                    {
                        existingDbSections[currentDb] = currentSection.ToString().Trim();
                    }
                    currentDb = line.Substring(13, line.Length - 14);
                    currentSection.Clear();
                    currentSection.AppendLine(line);
                }
                else if (currentDb != null)
                {
                    currentSection.AppendLine(line);
                }
            }
            if (currentDb != null && currentSection.Length > 0)
            {
                existingDbSections[currentDb] = currentSection.ToString().Trim();
            }
        }

        // Update or remove sections for the scanned databases
        foreach (var db in scanResult.Databases)
        {
            var validCrossDb = db.CrossDbDependencies
                .Where(d => !string.IsNullOrWhiteSpace(d.ReferencedDatabase) && !d.ReferencedDatabase.Equals(db.DatabaseName, StringComparison.OrdinalIgnoreCase))
                .ToList();

            if (validCrossDb.Count > 0)
            {
                var dbSb = new StringBuilder();
                dbSb.AppendLine($"## Database `{db.DatabaseName}`");
                var grouped = validCrossDb.GroupBy(d => d.ReferencedDatabase, StringComparer.OrdinalIgnoreCase);
                foreach (var grp in grouped)
                {
                    dbSb.AppendLine($"- References **`{grp.Key}`**:");
                    foreach (var item in grp)
                    {
                        dbSb.AppendLine($"  - `{db.DatabaseName}.{item.ReferencingEntity}` -> `{grp.Key}.{item.ReferencedEntity}`");
                    }
                }
                existingDbSections[db.DatabaseName] = dbSb.ToString().Trim();
            }
            else
            {
                existingDbSections.Remove(db.DatabaseName);
            }
        }

        var crossDbSb = new StringBuilder();
        crossDbSb.AppendLine($"# Cross-Database Dependencies Map: {scanResult.ServerAlias}");
        crossDbSb.AppendLine();
        crossDbSb.AppendLine("> Inter-database references found in stored procedures, views, and functions.");
        crossDbSb.AppendLine($"> Last updated: {scanResult.ScannedAt:yyyy-MM-dd HH:mm:ss}");
        crossDbSb.AppendLine();

        if (existingDbSections.Count > 0)
        {
            foreach (var kv in existingDbSections.OrderBy(k => k.Key))
            {
                crossDbSb.AppendLine(kv.Value);
                crossDbSb.AppendLine();
            }
        }
        else
        {
            crossDbSb.AppendLine("*(No cross-database dependencies detected)*");
            crossDbSb.AppendLine();
        }

        await File.WriteAllTextAsync(crossDbPath, crossDbSb.ToString(), Encoding.UTF8, cancellationToken);
        createdFiles.Add(crossDbPath);

        // 5. Write / Merge Server Overview summary.md
        var summaryPath = Path.Combine(serverDir, "summary.md");
        var existingSummaryRows = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (File.Exists(summaryPath))
        {
            var lines = await File.ReadAllLinesAsync(summaryPath, cancellationToken);
            foreach (var l in lines)
            {
                if (l.StartsWith("| **") && l.Contains("** |"))
                {
                    var endIdx = l.IndexOf("** |");
                    var db = l.Substring(4, endIdx - 4);
                    existingSummaryRows[db] = l;
                }
            }
        }

        foreach (var db in scanResult.Databases)
        {
            var status = db.Success ? "Success" : "Failed";
            var schemaLink = db.Success ? $"[databases/{db.DatabaseName}/schema.compact.md](./databases/{db.DatabaseName}/schema.compact.md)" : $"*(Error: {db.ErrorMessage})*";
            existingSummaryRows[db.DatabaseName] = $"| **{db.DatabaseName}** | {status} | {db.TableCount} | {db.ViewCount} | {db.ProcedureCount} | {db.FunctionCount} | {db.TriggerCount} | {schemaLink} |";
        }

        var summarySb = new StringBuilder();
        summarySb.AppendLine($"# Server Overview: {scanResult.ServerAlias}");
        summarySb.AppendLine();
        summarySb.AppendLine($"- **Host:** `{scanResult.ServerHost}`");
        summarySb.AppendLine($"- **SQL Version:** {scanResult.ServerVersion}");
        summarySb.AppendLine($"- **Scan Time:** {scanResult.ScannedAt:yyyy-MM-dd HH:mm:ss}");
        summarySb.AppendLine($"- **Execution Duration:** {scanResult.ElapsedMs} ms");
        summarySb.AppendLine($"- **Total Databases:** {existingSummaryRows.Count}");
        summarySb.AppendLine($"- **Fast Router Map (~20KB):** [TABLES_ROUTER.compact.md](./TABLES_ROUTER.compact.md)");
        summarySb.AppendLine($"- **Cross-DB Dependencies:** [CROSS_DB_DEPENDENCIES.compact.md](./CROSS_DB_DEPENDENCIES.compact.md)");
        summarySb.AppendLine($"- **SQLite Catalog (FTS5):** `../../catalog.db` (Searched instantly via tool `search_context`)");
        summarySb.AppendLine();
        summarySb.AppendLine("## Databases Overview");
        summarySb.AppendLine();
        summarySb.AppendLine("| Database | Status | Tables | Views | Procedures | Functions | Triggers | Schema Compact Link |");
        summarySb.AppendLine("|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---|");
        foreach (var kv in existingSummaryRows.OrderBy(k => k.Key))
        {
            summarySb.AppendLine(kv.Value);
        }

        await File.WriteAllTextAsync(summaryPath, summarySb.ToString(), Encoding.UTF8, cancellationToken);
        createdFiles.Add(summaryPath);

        // 6. Update Registry & Master INDEX.md
        var migrationsMap = new Dictionary<string, DatabaseMigrationStatus>(StringComparer.OrdinalIgnoreCase);
        foreach (var db in scanResult.Databases)
        {
            if (db.Success)
            {
                migrationsMap[db.DatabaseName] = new DatabaseMigrationStatus(
                    db.DatabaseName,
                    db.LatestMigrationId,
                    db.MigrationCount,
                    db.LastObjectModifyDate
                );
            }
        }

        var registryItem = new ServerRegistryItem(
            ServerAlias: scanResult.ServerAlias,
            ServerHost: scanResult.ServerHost,
            ServerVersion: scanResult.ServerVersion,
            DatabaseCount: existingSummaryRows.Count,
            TotalTableCount: scanTotalTables,
            TotalViewCount: scanTotalViews,
            TotalProcedureCount: scanTotalProcedures,
            LastScannedAt: scanResult.ScannedAt,
            TotalFunctionCount: scanTotalFunctions,
            TotalTriggerCount: scanTotalTriggers,
            Migrations: migrationsMap
        );

        var indexPath = await UpdateMasterIndexAsync(baseDir, registryItem, cancellationToken);
        createdFiles.Add(indexPath);

        return createdFiles;
    }

    public static async Task<string> UpdateCatalogDbAsync(
        string baseDir,
        string serverAlias,
        IEnumerable<DatabaseScanReport> databases,
        CancellationToken cancellationToken = default)
    {
        var dbPath = Path.Combine(baseDir, "catalog.db");
        await using var conn = new SqliteConnection($"Data Source={dbPath}");
        await conn.OpenAsync(cancellationToken);

        const string initSql = @"
CREATE TABLE IF NOT EXISTS catalog_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    server_alias TEXT NOT NULL,
    database_name TEXT NOT NULL,
    item_type TEXT NOT NULL,
    name TEXT NOT NULL,
    details TEXT,
    relative_path TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cat_alias_db ON catalog_items(server_alias, database_name);
CREATE INDEX IF NOT EXISTS idx_cat_server_db_type ON catalog_items(server_alias, database_name, item_type);
CREATE INDEX IF NOT EXISTS idx_cat_type ON catalog_items(item_type);
CREATE INDEX IF NOT EXISTS idx_cat_name ON catalog_items(name COLLATE NOCASE);
";
        await using (var initCmd = conn.CreateCommand())
        {
            initCmd.CommandText = initSql;
            await initCmd.ExecuteNonQueryAsync(cancellationToken);
        }

        await using var transaction = conn.BeginTransaction();

        foreach (var db in databases)
        {
            if (!db.Success) continue;

            // Delete old items for this server & DB
            await using (var delCmd = conn.CreateCommand())
            {
                delCmd.Transaction = transaction;
                delCmd.CommandText = "DELETE FROM catalog_items WHERE server_alias = @alias AND database_name = @db;";
                delCmd.Parameters.AddWithValue("@alias", serverAlias);
                delCmd.Parameters.AddWithValue("@db", db.DatabaseName);
                await delCmd.ExecuteNonQueryAsync(cancellationToken);
            }

            // Insert tables & columns
            foreach (var t in db.Tables)
            {
                var colsSummary = string.Join(", ", t.Columns.Select(c => c.ToQuickMapString()));
                var volInfo = t.ApproxRowCount.HasValue ? $" (~{t.ApproxRowCount.Value} rows)" : "";

                await using (var insCmd = conn.CreateCommand())
                {
                    insCmd.Transaction = transaction;
                    insCmd.CommandText = @"
INSERT INTO catalog_items (server_alias, database_name, item_type, name, details, relative_path)
VALUES (@alias, @db, 'table', @name, @details, @path);";
                    insCmd.Parameters.AddWithValue("@alias", serverAlias);
                    insCmd.Parameters.AddWithValue("@db", db.DatabaseName);
                    insCmd.Parameters.AddWithValue("@name", t.FullName);
                    insCmd.Parameters.AddWithValue("@details", $"{colsSummary}{volInfo}");
                    insCmd.Parameters.AddWithValue("@path", $"servers/{serverAlias}/databases/{db.DatabaseName}/schema.compact.md");
                    await insCmd.ExecuteNonQueryAsync(cancellationToken);
                }

                foreach (var col in t.Columns)
                {
                    await using var insColCmd = conn.CreateCommand();
                    insColCmd.Transaction = transaction;
                    insColCmd.CommandText = @"
INSERT INTO catalog_items (server_alias, database_name, item_type, name, details, relative_path)
VALUES (@alias, @db, 'column', @name, @details, @path);";
                    insColCmd.Parameters.AddWithValue("@alias", serverAlias);
                    insColCmd.Parameters.AddWithValue("@db", db.DatabaseName);
                    insColCmd.Parameters.AddWithValue("@name", $"{t.FullName}.{col.Name}");
                    var sampleStr = col.SampleValues != null && col.SampleValues.Count > 0 ? $" | Observed sample: [{string.Join(", ", col.SampleValues)}] (may be incomplete)" : "";
                    insColCmd.Parameters.AddWithValue("@details", $"{col.DataType} ({(col.IsPrimaryKey ? "PK, " : "")}{(col.IsNullable ? "Null" : "Not Null")}){sampleStr}");
                    insColCmd.Parameters.AddWithValue("@path", $"servers/{serverAlias}/databases/{db.DatabaseName}/schema.compact.md");
                    await insColCmd.ExecuteNonQueryAsync(cancellationToken);
                }
            }

            // Insert views
            foreach (var v in db.Views)
            {
                var fileName = SanitizeFileName($"{v.Schema}.{v.Name}.sql");
                await using var insViewCmd = conn.CreateCommand();
                insViewCmd.Transaction = transaction;
                insViewCmd.CommandText = @"
INSERT INTO catalog_items (server_alias, database_name, item_type, name, details, relative_path)
VALUES (@alias, @db, 'view', @name, @details, @path);";
                insViewCmd.Parameters.AddWithValue("@alias", serverAlias);
                insViewCmd.Parameters.AddWithValue("@db", db.DatabaseName);
                insViewCmd.Parameters.AddWithValue("@name", v.FullName);
                insViewCmd.Parameters.AddWithValue("@details", $"View in {db.DatabaseName}");
                insViewCmd.Parameters.AddWithValue("@path", $"servers/{serverAlias}/databases/{db.DatabaseName}/views/{fileName}");
                await insViewCmd.ExecuteNonQueryAsync(cancellationToken);
            }

            // Insert procedures
            foreach (var p in db.Procedures)
            {
                var fileName = SanitizeFileName($"{p.Schema}.{p.Name}.sql");
                var paramsStr = p.Parameters.Count > 0 ? string.Join(", ", p.Parameters) : "No params";
                await using var insProcCmd = conn.CreateCommand();
                insProcCmd.Transaction = transaction;
                insProcCmd.CommandText = @"
INSERT INTO catalog_items (server_alias, database_name, item_type, name, details, relative_path)
VALUES (@alias, @db, 'procedure', @name, @details, @path);";
                insProcCmd.Parameters.AddWithValue("@alias", serverAlias);
                insProcCmd.Parameters.AddWithValue("@db", db.DatabaseName);
                insProcCmd.Parameters.AddWithValue("@name", p.FullName);
                insProcCmd.Parameters.AddWithValue("@details", paramsStr);
                insProcCmd.Parameters.AddWithValue("@path", $"servers/{serverAlias}/databases/{db.DatabaseName}/procedures/{fileName}");
                await insProcCmd.ExecuteNonQueryAsync(cancellationToken);
            }

            // Insert functions
            foreach (var f in db.Functions)
            {
                var fileName = SanitizeFileName($"{f.Schema}.{f.Name}.sql");
                await using var insFuncCmd = conn.CreateCommand();
                insFuncCmd.Transaction = transaction;
                insFuncCmd.CommandText = @"
INSERT INTO catalog_items (server_alias, database_name, item_type, name, details, relative_path)
VALUES (@alias, @db, 'function', @name, @details, @path);";
                insFuncCmd.Parameters.AddWithValue("@alias", serverAlias);
                insFuncCmd.Parameters.AddWithValue("@db", db.DatabaseName);
                insFuncCmd.Parameters.AddWithValue("@name", f.FullName);
                insFuncCmd.Parameters.AddWithValue("@details", f.TypeDesc);
                insFuncCmd.Parameters.AddWithValue("@path", $"servers/{serverAlias}/databases/{db.DatabaseName}/functions/{fileName}");
                await insFuncCmd.ExecuteNonQueryAsync(cancellationToken);
            }

            // Insert triggers
            foreach (var trg in db.Triggers)
            {
                var fileName = SanitizeFileName($"{trg.Schema}.{trg.Name}.sql");
                await using var insTrgCmd = conn.CreateCommand();
                insTrgCmd.Transaction = transaction;
                insTrgCmd.CommandText = @"
INSERT INTO catalog_items (server_alias, database_name, item_type, name, details, relative_path)
VALUES (@alias, @db, 'trigger', @name, @details, @path);";
                insTrgCmd.Parameters.AddWithValue("@alias", serverAlias);
                insTrgCmd.Parameters.AddWithValue("@db", db.DatabaseName);
                insTrgCmd.Parameters.AddWithValue("@name", trg.FullName);
                insTrgCmd.Parameters.AddWithValue("@details", $"Trigger on [{trg.TargetTable}] ({trg.Events})");
                insTrgCmd.Parameters.AddWithValue("@path", $"servers/{serverAlias}/databases/{db.DatabaseName}/triggers/{fileName}");
                await insTrgCmd.ExecuteNonQueryAsync(cancellationToken);
            }
        }

        try
        {
            await using var syncFts = conn.CreateCommand();
            syncFts.Transaction = transaction;
            syncFts.CommandText = "INSERT INTO catalog_fts(catalog_fts) VALUES('rebuild');";
            await syncFts.ExecuteNonQueryAsync(cancellationToken);
        }
        catch
        {
            // Ignore if rebuild command unsupported
        }

        await transaction.CommitAsync(cancellationToken);
        return dbPath;
    }

    public static string RenderCompactSchema(string serverAlias, DatabaseScanReport db)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Database Schema: {db.DatabaseName} (Server: {serverAlias})");
        sb.AppendLine();
        sb.AppendLine($"> Statistics: **{db.TableCount}** Tables | **{db.ViewCount}** Views | **{db.ProcedureCount}** Stored Procedures | **{db.FunctionCount}** Functions | **{db.TriggerCount}** Triggers");
        if (!string.IsNullOrEmpty(db.LatestMigrationId))
        {
            sb.AppendLine($"> Migration: Latest = `{db.LatestMigrationId}` ({db.MigrationCount} total)");
        }
        sb.AppendLine("> Token-optimized compact format for AI Agent schema lookup.");
        sb.AppendLine();

        sb.AppendLine("## 1. Tables");
        sb.AppendLine();
        if (db.Tables.Count == 0)
        {
            sb.AppendLine("*(No tables found or login lacks metadata permissions)*");
        }
        else
        {
            foreach (var table in db.Tables)
            {
                var volSuffix = "";
                if (table.ApproxRowCount.HasValue)
                {
                    var r = table.ApproxRowCount.Value;
                    var rStr = r >= 1_000_000
                        ? (r / 1_000_000.0).ToString("0.0", System.Globalization.CultureInfo.InvariantCulture) + "M"
                        : r >= 1_000
                            ? (r / 1_000.0).ToString("0.0", System.Globalization.CultureInfo.InvariantCulture) + "K"
                            : $"{r}";
                    var sStr = table.ApproxSizeMb.HasValue
                        ? $" | {table.ApproxSizeMb.Value.ToString("0.0", System.Globalization.CultureInfo.InvariantCulture)} MB"
                        : "";
                    var highVol = r >= 100_000 ? " [HIGH VOLUME]" : "";
                    volSuffix = $" (~{rStr} rows{sStr}){highVol}";
                }
                else
                {
                    volSuffix = " (Stats: unavailable)";
                }

                sb.AppendLine($"### {table.FullName}{volSuffix}");
                foreach (var col in table.Columns)
                {
                    sb.AppendLine(col.ToCompactString());
                }

                if (table.CheckConstraints.Count > 0)
                {
                    var checksStr = string.Join("; ", table.CheckConstraints.Select(c => c.ToCompactString()));
                    sb.AppendLine($"- Check Constraints: {checksStr}");
                }

                if (table.Indexes.Count > 0)
                {
                    var idxStr = string.Join("; ", table.Indexes.Select(i => i.ToCompactString()));
                    sb.AppendLine($"- Indexes: {idxStr}");
                }

                if (table.Triggers.Count > 0)
                {
                    var trgStr = string.Join("; ", table.Triggers.Select(t => $"{t.Name} ({t.Events})"));
                    sb.AppendLine($"- Triggers: {trgStr}");
                }

                sb.AppendLine();
            }
        }

        sb.AppendLine("## 2. Views Summary");
        sb.AppendLine();
        if (db.Views.Count == 0)
        {
            sb.AppendLine("*(No views found)*");
        }
        else
        {
            foreach (var view in db.Views)
            {
                var viewFile = SanitizeFileName($"{view.Schema}.{view.Name}.sql");
                sb.AppendLine($"- **`{view.FullName}`** -> [View SQL definition](./views/{viewFile})");
            }
        }
        sb.AppendLine();

        sb.AppendLine("## 3. Stored Procedures Summary");
        sb.AppendLine();
        if (db.Procedures.Count == 0)
        {
            sb.AppendLine("*(No stored procedures found)*");
        }
        else
        {
            foreach (var proc in db.Procedures)
            {
                var procFile = SanitizeFileName($"{proc.Schema}.{proc.Name}.sql");
                var paramStr = proc.Parameters.Count > 0 ? $"({string.Join(", ", proc.Parameters.Take(3))}{(proc.Parameters.Count > 3 ? ", ..." : "")})" : "()";
                sb.AppendLine($"- **`{proc.FullName}`** `{paramStr}` -> [Procedure SQL definition](./procedures/{procFile})");
            }
        }
        sb.AppendLine();

        sb.AppendLine("## 4. Functions Summary");
        sb.AppendLine();
        if (db.Functions.Count == 0)
        {
            sb.AppendLine("*(No functions found)*");
        }
        else
        {
            foreach (var func in db.Functions)
            {
                var funcFile = SanitizeFileName($"{func.Schema}.{func.Name}.sql");
                var paramStr = func.Parameters.Count > 0 ? $"({string.Join(", ", func.Parameters)})" : "()";
                sb.AppendLine($"- **`{func.FullName}`** `{paramStr}` ({func.TypeDesc}) -> [Function SQL definition](./functions/{funcFile})");
            }
        }
        sb.AppendLine();

        sb.AppendLine("## 5. Triggers Summary");
        sb.AppendLine();
        if (db.Triggers.Count == 0)
        {
            sb.AppendLine("*(No triggers found)*");
        }
        else
        {
            foreach (var trg in db.Triggers)
            {
                var trgFile = SanitizeFileName($"{trg.Schema}.{trg.Name}.sql");
                var disabledStr = trg.IsDisabled ? " [DISABLED]" : "";
                sb.AppendLine($"- **`{trg.FullName}`** on `[{trg.TargetTable}]` ({trg.Events}){disabledStr} -> [View SQL definition](./triggers/{trgFile})");
            }
        }

        return sb.ToString();
    }

    private static async Task<string> UpdateMasterIndexAsync(
        string baseDir,
        ServerRegistryItem newItem,
        CancellationToken cancellationToken)
    {
        var registryPath = Path.Combine(baseDir, "servers_registry.json");
        var registry = new Dictionary<string, ServerRegistryItem>(StringComparer.OrdinalIgnoreCase);

        if (File.Exists(registryPath))
        {
            try
            {
                var json = await File.ReadAllTextAsync(registryPath, cancellationToken);
                var items = JsonSerializer.Deserialize<List<ServerRegistryItem>>(json);
                if (items != null)
                {
                    foreach (var item in items)
                    {
                        registry[item.ServerAlias] = item;
                    }
                }
            }
            catch
            {
                // Fallback if file is corrupted
            }
        }

        // Merge migrations if existing item has older entries
        if (registry.TryGetValue(newItem.ServerAlias, out var existingItem) && existingItem.Migrations != null)
        {
            var merged = new Dictionary<string, DatabaseMigrationStatus>(existingItem.Migrations, StringComparer.OrdinalIgnoreCase);
            if (newItem.Migrations != null)
            {
                foreach (var kv in newItem.Migrations)
                {
                    merged[kv.Key] = kv.Value;
                }
            }
            newItem = newItem with { Migrations = merged };
        }

        registry[newItem.ServerAlias] = newItem;

        var orderedItems = registry.Values.OrderBy(x => x.ServerAlias).ToList();
        var serializedRegistry = JsonSerializer.Serialize(orderedItems, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(registryPath, serializedRegistry, Encoding.UTF8, cancellationToken);

        // Render Master INDEX.md
        var indexSb = new StringBuilder();
        indexSb.AppendLine("# AI Context Master Index");
        indexSb.AppendLine();
        indexSb.AppendLine("> Central map of all SQL Server Instances for high-speed, token-optimized AI Agent lookup.");
        indexSb.AppendLine($"> Last updated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        indexSb.AppendLine();
        indexSb.AppendLine("## 1. Servers & Environments");
        indexSb.AppendLine();
        indexSb.AppendLine("| Server Alias | Host | Version | Databases | Tables | Views | SPs | Functions | Triggers | Last Scanned | Server Docs |");
        indexSb.AppendLine("|:---|:---|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---|:---|");

        foreach (var item in orderedItems)
        {
            var serverDocLink = $"[View Server {item.ServerAlias}](./servers/{item.ServerAlias}/summary.md)";
            var versionShort = item.ServerVersion.Split('\n')[0].Trim();
            if (versionShort.Length > 30) versionShort = versionShort[..27] + "...";

            indexSb.AppendLine($"| **{item.ServerAlias}** | `{item.ServerHost}` | {versionShort} | {item.DatabaseCount} | {item.TotalTableCount} | {item.TotalViewCount} | {item.TotalProcedureCount} | {item.TotalFunctionCount} | {item.TotalTriggerCount} | {item.LastScannedAt:yyyy-MM-dd HH:mm} | {serverDocLink} |");
        }

        indexSb.AppendLine();
        indexSb.AppendLine("## 2. Token-Optimized AI Agent Debug & Troubleshooting Workflow");
        indexSb.AppendLine();
        indexSb.AppendLine("> 💡 **CRITICAL TOKEN RULE**: Zero Token Waste. High-speed lookup via SQLite catalog.");
        indexSb.AppendLine();
        indexSb.AppendLine("1. **Instant Search (<1ms, ~50 tokens):** Call MCP tool `search_context(query: \"...\")` to locate exact DB, Table, Column, Procedure, Function, or Trigger from local SQLite `catalog.db`.");
        indexSb.AppendLine("2. **Low-Token Table Routing (~4,000 tokens):** If searching manually, open `./servers/{ALIAS}/TABLES_ROUTER.compact.md` (~20KB) to find the hosting database.");
        indexSb.AppendLine("3. **Inspect Compact Schema:** Open `./servers/{ALIAS}/databases/{DB_NAME}/schema.compact.md` for column types, volume stats (~rows/MB), defaults, constraints, PK, FK, and indexes.");
        indexSb.AppendLine("4. **Inspect Routine Logic:** Open targeted SQL files in `views/`, `procedures/`, `functions/`, or `triggers/`.");
        indexSb.AppendLine("5. **Inspect Cross-DB Relations:** Check `./servers/{ALIAS}/CROSS_DB_DEPENDENCIES.compact.md` for inter-database references.");
        indexSb.AppendLine("6. **Detect Drift / Migrations:** Call MCP tool `check_schema_drift` or use CLI option `[3] Check DB Migration Drift`.");
        indexSb.AppendLine("7. **Query Live Data:** Call MCP tool `execute_query` with a read-only SELECT query to inspect real rows.");

        var masterIndexPath = Path.Combine(baseDir, "INDEX.md");
        await File.WriteAllTextAsync(masterIndexPath, indexSb.ToString(), Encoding.UTF8, cancellationToken);

        return masterIndexPath;
    }

    public static async Task<SearchContextResult> SearchContextAsync(
        string baseDirectory,
        string query,
        string? database = null,
        string? target = "all",
        int limit = 10,
        string? serverAlias = null,
        bool includeDetails = false,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(query))
        {
            return new SearchContextResult(query, 0, Array.Empty<SearchContextMatch>(), "Query string cannot be empty.");
        }

        var fullBaseDir = Path.GetFullPath(baseDirectory);
        var catalogPath = Path.Combine(fullBaseDir, "catalog.db");
        if (!File.Exists(catalogPath))
        {
            return new SearchContextResult(query, 0, Array.Empty<SearchContextMatch>(), "No ai-context catalog found. Please run 'scan_server_context' tool first.");
        }

        var q = query.Trim();
        var targetType = string.IsNullOrWhiteSpace(target) ? "all" : target.Trim().ToLowerInvariant();
        var matches = new List<SearchContextMatch>();

        try
        {
            await using var conn = new SqliteConnection($"Data Source={catalogPath}");
            await conn.OpenAsync(cancellationToken);

            var querySql = @"
SELECT server_alias, database_name, item_type, name, details, relative_path
FROM catalog_items
WHERE (@server IS NULL OR server_alias = @server COLLATE NOCASE)
  AND (@db IS NULL OR database_name = @db COLLATE NOCASE)
  AND (
    @type = 'all' 
    OR item_type = @type 
    OR (@type = 'routine' AND item_type IN ('procedure', 'view', 'function', 'trigger'))
  )
  AND (name LIKE @pattern ESCAPE '\' OR details LIKE @pattern ESCAPE '\')
ORDER BY 
  CASE WHEN name = @exact COLLATE NOCASE THEN 1
       WHEN name LIKE @prefix COLLATE NOCASE THEN 2
       ELSE 3 END,
  item_type, name
LIMIT @limit;";

            var escapedQ = q.Replace(@"\", @"\\").Replace("%", @"\%").Replace("_", @"\_");
            var pattern = $"%{escapedQ}%";
            var prefix = $"{escapedQ}%";

            await using (var cmd = conn.CreateCommand())
            {
                cmd.CommandText = querySql;
                cmd.Parameters.AddWithValue("@server", (object?)serverAlias ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@db", (object?)database ?? DBNull.Value);
                cmd.Parameters.AddWithValue("@type", targetType);
                cmd.Parameters.AddWithValue("@pattern", pattern);
                cmd.Parameters.AddWithValue("@prefix", prefix);
                cmd.Parameters.AddWithValue("@exact", q);
                cmd.Parameters.AddWithValue("@limit", Math.Clamp(limit, 1, 50));

                await using var reader = await cmd.ExecuteReaderAsync(cancellationToken);
                while (await reader.ReadAsync(cancellationToken))
                {
                    matches.Add(new SearchContextMatch(
                        ServerAlias: reader.GetString(0),
                        Database: reader.GetString(1),
                        Type: reader.GetString(2),
                        Name: reader.GetString(3),
                        Details: includeDetails && !reader.IsDBNull(4) ? reader.GetString(4) : "",
                        RelativePath: reader.GetString(5)
                    ));
                }
            }
        }
        catch (Exception ex)
        {
            return new SearchContextResult(q, 0, Array.Empty<SearchContextMatch>(), $"Error querying catalog: {ex.Message}");
        }

        return new SearchContextResult(
            Query: q,
            TotalMatches: matches.Count,
            Matches: matches,
            Message: matches.Count == 0
                ? $"No matches found for '{q}'."
                : $"Found {matches.Count} match(es) for '{q}'."
        );
    }

    public static async Task<string> GetObjectContextAsync(
        string baseDirectory,
        string serverAlias,
        string database,
        string objectName,
        string? objectType = null,
        CancellationToken cancellationToken = default)
    {
        var fullBaseDir = Path.GetFullPath(baseDirectory);
        var dbDir = Path.Combine(fullBaseDir, "servers", serverAlias, "databases", database);
        if (!Directory.Exists(dbDir))
        {
            return $"Database '{database}' on server '{serverAlias}' not found in ai-context snapshot.";
        }

        var normalizedName = objectName.Trim().Trim('[', ']');
        var pureName = normalizedName.Contains('.') ? normalizedName.Substring(normalizedName.LastIndexOf('.') + 1) : normalizedName;
        var type = objectType?.Trim().ToLowerInvariant();

        // 1. If table or unspecified, search in schema.compact.md
        if (type == "table" || string.IsNullOrEmpty(type))
        {
            var schemaFile = Path.Combine(dbDir, "schema.compact.md");
            if (File.Exists(schemaFile))
            {
                var lines = await File.ReadAllLinesAsync(schemaFile, cancellationToken);
                var section = new StringBuilder();
                bool recording = false;
                foreach (var line in lines)
                {
                    if (line.StartsWith("### ") && (line.Contains($".{pureName} ") || line.EndsWith($".{pureName}") || line.Contains($".{pureName}(")))
                    {
                        recording = true;
                        section.AppendLine(line);
                        continue;
                    }
                    if (recording)
                    {
                        if (line.StartsWith("### ") || line.StartsWith("## ")) break;
                        section.AppendLine(line);
                    }
                }
                if (section.Length > 0) return section.ToString().TrimEnd();
            }
        }

        // 2. Check routine SQL files (views, procedures, functions, triggers)
        var routineFolders = new[] { "procedures", "views", "functions", "triggers" };
        foreach (var folder in routineFolders)
        {
            if (!string.IsNullOrEmpty(type) && !folder.StartsWith(type)) continue;

            var folderPath = Path.Combine(dbDir, folder);
            if (Directory.Exists(folderPath))
            {
                var match = Directory.GetFiles(folderPath, $"*.{pureName}.sql")
                    .Concat(Directory.GetFiles(folderPath, $"{pureName}.sql"))
                    .FirstOrDefault();

                if (match != null)
                {
                    return await File.ReadAllTextAsync(match, cancellationToken);
                }
            }
        }

        // 3. Check cross-db dependencies
        if (type == "dependency" || string.IsNullOrEmpty(type))
        {
            var crossDbPath = Path.Combine(fullBaseDir, "servers", serverAlias, "CROSS_DB_DEPENDENCIES.compact.md");
            if (File.Exists(crossDbPath))
            {
                var lines = await File.ReadAllLinesAsync(crossDbPath, cancellationToken);
                var matchingLines = lines.Where(l => l.Contains(pureName, StringComparison.OrdinalIgnoreCase)).ToList();
                if (matchingLines.Count > 0)
                {
                    return $"### Cross-Database Dependencies for '{pureName}':\n" + string.Join("\n", matchingLines);
                }
            }
        }

        return $"Object '{objectName}' not found in ai-context snapshot for {serverAlias}/{database}.";
    }

    private static void CleanupOrphanSqlFiles(string directory, IEnumerable<string> activeFileNames)
    {
        if (!Directory.Exists(directory)) return;
        var activeSet = new HashSet<string>(activeFileNames, StringComparer.OrdinalIgnoreCase);
        foreach (var file in Directory.GetFiles(directory, "*.sql"))
        {
            var fileName = Path.GetFileName(file);
            if (!activeSet.Contains(fileName))
            {
                try { File.Delete(file); } catch { }
            }
        }
    }

    private static string SanitizeFileName(string fileName)
    {
        var invalid = Path.GetInvalidFileNameChars();
        return string.Concat(fileName.Select(c => invalid.Contains(c) ? '_' : c));
    }
}
