using System.Text;
using System.Text.Json;

namespace McpSqlServer;

public record ServerRegistryItem(
    string ServerAlias,
    string ServerHost,
    string ServerVersion,
    int DatabaseCount,
    int TotalTableCount,
    int TotalViewCount,
    int TotalProcedureCount,
    DateTime LastScannedAt
);

public class AiContextRenderer
{
    public static async Task<IReadOnlyList<string>> RenderAndExportAsync(
        ServerScanResult scanResult,
        string outputDirectory = "./ai-context",
        CancellationToken cancellationToken = default)
    {
        var createdFiles = new List<string>();
        var baseDir = Path.GetFullPath(outputDirectory);
        var serversDir = Path.Combine(baseDir, "servers");
        var serverDir = Path.Combine(serversDir, scanResult.ServerAlias);

        Directory.CreateDirectory(serverDir);

        int totalTables = 0;
        int totalViews = 0;
        int totalProcedures = 0;

        // 1. Render each Database & Compile Global Tables Map
        var globalMapSb = new StringBuilder();
        globalMapSb.AppendLine($"# Global Tables Map: {scanResult.ServerAlias}");
        globalMapSb.AppendLine();
        globalMapSb.AppendLine($"> Single-line index per table for ultra-fast reverse lookup (grep_search) on Server [{scanResult.ServerAlias}].");
        globalMapSb.AppendLine($"> Last updated: {scanResult.ScannedAt:yyyy-MM-dd HH:mm:ss}");
        globalMapSb.AppendLine();

        var dbSummaries = new StringBuilder();
        dbSummaries.AppendLine($"# Server Overview: {scanResult.ServerAlias}");
        dbSummaries.AppendLine();
        dbSummaries.AppendLine($"- **Host:** `{scanResult.ServerHost}`");
        dbSummaries.AppendLine($"- **SQL Version:** {scanResult.ServerVersion}");
        dbSummaries.AppendLine($"- **Scan Time:** {scanResult.ScannedAt:yyyy-MM-dd HH:mm:ss}");
        dbSummaries.AppendLine($"- **Execution Duration:** {scanResult.ElapsedMs} ms");
        dbSummaries.AppendLine($"- **Total Databases:** {scanResult.Databases.Count}");
        dbSummaries.AppendLine($"- **Fast Lookup Map:** [GLOBAL_TABLES_MAP.compact.md](./GLOBAL_TABLES_MAP.compact.md) (Fast grep for tables & columns across instance)");
        dbSummaries.AppendLine();
        dbSummaries.AppendLine("## Databases Overview");
        dbSummaries.AppendLine();
        dbSummaries.AppendLine("| Database | Status | Tables | Views | Procedures | Schema Compact Link |");
        dbSummaries.AppendLine("|:---|:---:|:---:|:---:|:---:|:---|");

        foreach (var db in scanResult.Databases)
        {
            cancellationToken.ThrowIfCancellationRequested();

            totalTables += db.TableCount;
            totalViews += db.ViewCount;
            totalProcedures += db.ProcedureCount;

            var status = db.Success ? "Success" : "Failed";
            var schemaLink = db.Success ? $"[databases/{db.DatabaseName}/schema.compact.md](./databases/{db.DatabaseName}/schema.compact.md)" : $"*(Error: {db.ErrorMessage})*";
            dbSummaries.AppendLine($"| **{db.DatabaseName}** | {status} | {db.TableCount} | {db.ViewCount} | {db.ProcedureCount} | {schemaLink} |");

            if (!db.Success) continue;

            // Add to Global Tables Map
            foreach (var table in db.Tables)
            {
                var colsStr = string.Join(", ", table.Columns.Select(c => c.ToQuickMapString()));
                globalMapSb.AppendLine($"- `{db.DatabaseName}.{table.FullName}`: {colsStr}");
            }

            var dbDir = Path.Combine(serverDir, "databases", db.DatabaseName);
            var viewsDir = Path.Combine(dbDir, "views");
            var procsDir = Path.Combine(dbDir, "procedures");

            Directory.CreateDirectory(dbDir);
            if (db.Views.Count > 0) Directory.CreateDirectory(viewsDir);
            if (db.Procedures.Count > 0) Directory.CreateDirectory(procsDir);

            // Write schema.compact.md
            var compactSchemaPath = Path.Combine(dbDir, "schema.compact.md");
            var compactContent = RenderCompactSchema(scanResult.ServerAlias, db);
            await File.WriteAllTextAsync(compactSchemaPath, compactContent, Encoding.UTF8, cancellationToken);
            createdFiles.Add(compactSchemaPath);

            // Write individual View SQL files
            foreach (var view in db.Views)
            {
                var safeViewName = SanitizeFileName($"{view.Schema}.{view.Name}.sql");
                var viewPath = Path.Combine(viewsDir, safeViewName);
                var viewSql = $"-- Server: {scanResult.ServerAlias} | DB: {db.DatabaseName} | View: {view.FullName}\n" +
                              $"-- Auto-generated by MCP SQL Server\n\n" +
                              (view.Definition ?? "-- [No definition available]");
                await File.WriteAllTextAsync(viewPath, viewSql, Encoding.UTF8, cancellationToken);
                createdFiles.Add(viewPath);
            }

            // Write individual Procedure SQL files
            foreach (var proc in db.Procedures)
            {
                var safeProcName = SanitizeFileName($"{proc.Schema}.{proc.Name}.sql");
                var procPath = Path.Combine(procsDir, safeProcName);
                var paramsHeader = proc.Parameters.Count > 0
                    ? $"-- Parameters:\n" + string.Join("\n", proc.Parameters.Select(p => $"--   {p}")) + "\n"
                    : "-- Parameters: (None)\n";

                var procSql = $"-- Server: {scanResult.ServerAlias} | DB: {db.DatabaseName} | Procedure: {proc.FullName}\n" +
                              paramsHeader +
                              $"-- Auto-generated by MCP SQL Server\n\n" +
                              (proc.Definition ?? "-- [No definition available]");
                await File.WriteAllTextAsync(procPath, procSql, Encoding.UTF8, cancellationToken);
                createdFiles.Add(procPath);
            }
        }

        // Write servers/{ServerAlias}/GLOBAL_TABLES_MAP.compact.md
        var globalMapPath = Path.Combine(serverDir, "GLOBAL_TABLES_MAP.compact.md");
        await File.WriteAllTextAsync(globalMapPath, globalMapSb.ToString(), Encoding.UTF8, cancellationToken);
        createdFiles.Add(globalMapPath);

        // Write servers/{ServerAlias}/summary.md
        var serverSummaryPath = Path.Combine(serverDir, "summary.md");
        await File.WriteAllTextAsync(serverSummaryPath, dbSummaries.ToString(), Encoding.UTF8, cancellationToken);
        createdFiles.Add(serverSummaryPath);

        // 2. Update Registry & Master INDEX.md
        var registryItem = new ServerRegistryItem(
            ServerAlias: scanResult.ServerAlias,
            ServerHost: scanResult.ServerHost,
            ServerVersion: scanResult.ServerVersion,
            DatabaseCount: scanResult.Databases.Count,
            TotalTableCount: totalTables,
            TotalViewCount: totalViews,
            TotalProcedureCount: totalProcedures,
            LastScannedAt: scanResult.ScannedAt
        );

        var indexPath = await UpdateMasterIndexAsync(baseDir, registryItem, cancellationToken);
        createdFiles.Add(indexPath);

        return createdFiles;
    }

    public static string RenderCompactSchema(string serverAlias, DatabaseScanReport db)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Database Schema: {db.DatabaseName} (Server: {serverAlias})");
        sb.AppendLine();
        sb.AppendLine($"> Statistics: **{db.TableCount}** Tables | **{db.ViewCount}** Views | **{db.ProcedureCount}** Stored Procedures");
        sb.AppendLine("> Token-optimized compact format for AI Agent schema lookup.");
        sb.AppendLine();

        sb.AppendLine("## 1. Tables");
        sb.AppendLine();
        if (db.Tables.Count == 0)
        {
            sb.AppendLine("*(No tables found or login lacks metadata permissions)*");
        }
        else
        {
            foreach (var table in db.Tables)
            {
                sb.AppendLine($"### {table.FullName}");
                foreach (var col in table.Columns)
                {
                    sb.AppendLine(col.ToCompactString());
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("## 2. Views Summary");
        sb.AppendLine();
        if (db.Views.Count == 0)
        {
            sb.AppendLine("*(No views found)*");
        }
        else
        {
            foreach (var view in db.Views)
            {
                var viewFile = SanitizeFileName($"{view.Schema}.{view.Name}.sql");
                sb.AppendLine($"- **`{view.FullName}`** -> [View SQL definition](./views/{viewFile})");
            }
        }
        sb.AppendLine();

        sb.AppendLine("## 3. Stored Procedures Summary");
        sb.AppendLine();
        if (db.Procedures.Count == 0)
        {
            sb.AppendLine("*(No stored procedures found)*");
        }
        else
        {
            foreach (var proc in db.Procedures)
            {
                var procFile = SanitizeFileName($"{proc.Schema}.{proc.Name}.sql");
                var paramList = proc.Parameters.Count > 0 ? $"({string.Join(", ", proc.Parameters)})" : "()";
                sb.AppendLine($"- **`{proc.FullName}`** `{paramList}` -> [View SQL definition](./procedures/{procFile})");
            }
        }

        return sb.ToString();
    }

    private static async Task<string> UpdateMasterIndexAsync(
        string baseDir,
        ServerRegistryItem newItem,
        CancellationToken cancellationToken)
    {
        var registryPath = Path.Combine(baseDir, "servers_registry.json");
        var registry = new Dictionary<string, ServerRegistryItem>(StringComparer.OrdinalIgnoreCase);

        if (File.Exists(registryPath))
        {
            try
            {
                var json = await File.ReadAllTextAsync(registryPath, cancellationToken);
                var items = JsonSerializer.Deserialize<List<ServerRegistryItem>>(json);
                if (items != null)
                {
                    foreach (var item in items)
                    {
                        registry[item.ServerAlias] = item;
                    }
                }
            }
            catch
            {
                // Fallback if file is corrupted
            }
        }

        registry[newItem.ServerAlias] = newItem;

        var orderedItems = registry.Values.OrderBy(x => x.ServerAlias).ToList();
        var serializedRegistry = JsonSerializer.Serialize(orderedItems, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(registryPath, serializedRegistry, Encoding.UTF8, cancellationToken);

        // Render Master INDEX.md
        var indexSb = new StringBuilder();
        indexSb.AppendLine("# AI Context Master Index");
        indexSb.AppendLine();
        indexSb.AppendLine("> Central map of all SQL Server Instances for high-speed, token-optimized AI Agent lookup.");
        indexSb.AppendLine($"> Last updated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        indexSb.AppendLine();
        indexSb.AppendLine("## 1. Servers & Environments");
        indexSb.AppendLine();
        indexSb.AppendLine("| Server Alias | Host | Version | Databases | Tables | Views | SPs | Last Scanned | Server Docs |");
        indexSb.AppendLine("|:---|:---|:---|:---:|:---:|:---:|:---:|:---|:---|");

        foreach (var item in orderedItems)
        {
            var serverDocLink = $"[View Server {item.ServerAlias}](./servers/{item.ServerAlias}/summary.md)";
            var versionShort = item.ServerVersion.Split('\n')[0].Trim();
            if (versionShort.Length > 30) versionShort = versionShort[..27] + "...";

            indexSb.AppendLine($"| **{item.ServerAlias}** | `{item.ServerHost}` | {versionShort} | {item.DatabaseCount} | {item.TotalTableCount} | {item.TotalViewCount} | {item.TotalProcedureCount} | {item.LastScannedAt:yyyy-MM-dd HH:mm} | {serverDocLink} |");
        }

        indexSb.AppendLine();
        indexSb.AppendLine("## 2. AI Agent Context Lookup & Troubleshooting Workflow");
        indexSb.AppendLine("1. **Instant Table/Column Lookup (0.1s):** Open or grep keywords (e.g. `schedule`, `report_id`) in `./servers/{ALIAS}/GLOBAL_TABLES_MAP.compact.md` to immediately locate target Database and Table.");
        indexSb.AppendLine("2. **Inspect Compact Schema:** Open `./servers/{ALIAS}/databases/{DB_NAME}/schema.compact.md` for column types, PK, FK, and descriptions.");
        indexSb.AppendLine("3. **Inspect Routine Logic:** Open corresponding SQL files in `views/` or `procedures/`.");
        indexSb.AppendLine("4. **Query Live Data:** Call MCP Tool `execute_query` with a read-only SELECT query to inspect real rows causing the bug.");
        indexSb.AppendLine("5. **Compare Environments:** Compare `schema.compact.md` between DEV and PROD to detect schema drift.");

        var masterIndexPath = Path.Combine(baseDir, "INDEX.md");
        await File.WriteAllTextAsync(masterIndexPath, indexSb.ToString(), Encoding.UTF8, cancellationToken);

        return masterIndexPath;
    }

    private static string SanitizeFileName(string fileName)
    {
        var invalid = Path.GetInvalidFileNameChars();
        return string.Concat(fileName.Select(c => invalid.Contains(c) ? '_' : c));
    }
}
